// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLMkK6gEpvxqex33FQv2lpjeaLZ_xyydQ',
    appId: '1:55849483629:web:4fe3ebcf1aa2a4b81fae64',
    messagingSenderId: '55849483629',
    projectId: 'hack-fusion-95272',
    authDomain: 'hack-fusion-95272.firebaseapp.com',
    storageBucket: 'hack-fusion-95272.firebasestorage.app',
    measurementId: 'G-VTHJYZC4MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-wqMMSOw3KeY0Nq6ju1A6PZEQsgd021A',
    appId: '1:55849483629:android:ff1afb6d1c4ed3631fae64',
    messagingSenderId: '55849483629',
    projectId: 'hack-fusion-95272',
    storageBucket: 'hack-fusion-95272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGwXhKcW1_brs9G39qGlDaXB90q3mgDsk',
    appId: '1:55849483629:ios:abedf11b8a5a9f201fae64',
    messagingSenderId: '55849483629',
    projectId: 'hack-fusion-95272',
    storageBucket: 'hack-fusion-95272.firebasestorage.app',
    iosBundleId: 'com.example.hackFusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGwXhKcW1_brs9G39qGlDaXB90q3mgDsk',
    appId: '1:55849483629:ios:abedf11b8a5a9f201fae64',
    messagingSenderId: '55849483629',
    projectId: 'hack-fusion-95272',
    storageBucket: 'hack-fusion-95272.firebasestorage.app',
    iosBundleId: 'com.example.hackFusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLMkK6gEpvxqex33FQv2lpjeaLZ_xyydQ',
    appId: '1:55849483629:web:528850e557a300c81fae64',
    messagingSenderId: '55849483629',
    projectId: 'hack-fusion-95272',
    authDomain: 'hack-fusion-95272.firebaseapp.com',
    storageBucket: 'hack-fusion-95272.firebasestorage.app',
    measurementId: 'G-9QE1MXF71D',
  );
}
